name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.20.7, 20.18.3, 22.14.0] # Hydrogen, Iron, Jod
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
